[project]
name = "knowledge-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "吴柯", email = "2248914366@qq.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
knowledge-base = "knowledge_base:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
